# Generated by Django 5.0.1 on 2024-01-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_funds_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('USDT_TRC20', 'USDT TRC20'), ('USDT_ERC20', 'USDT ERC20'), ('BTC', 'BTC')], max_length=20, unique=True)),
                ('total_amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Approved Funds',
                'verbose_name_plural': 'Approved Funds',
            },
        ),
    ]
