# Generated by Django 5.0.1 on 2024-01-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_accountsummary_delete_approvedfunds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsummary',
            name='account_type',
            field=models.CharField(blank=True, choices=[('USDT_TRC20', 'USDT TRC20'), ('USDT_ERC20', 'USDT ERC20'), ('BTC', 'BTC')], max_length=20, null=True, unique=True),
        ),
    ]
