# Generated by Django 5.0.1 on 2024-01-17 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('For Sell', 'For Sell'), ('For Rent', 'For Rent')], max_length=20)),
                ('image', models.ImageField(upload_to='property_images/')),
                ('purpose', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Building', 'Building'), ('Townhouse', 'Townhouse'), ('Home', 'Home'), ('Shop', 'Shop'), ('Office', 'Office'), ('Garage', 'Garage')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('width_in_sqft', models.FloatField()),
                ('no_of_bed', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_bath', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_percentage', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Fast Growing', 'Fast Growing'), ('Hot Assets', 'Hot Assets'), ('Most Invested', 'Most Invested')], max_length=20)),
                ('investors_count', models.PositiveIntegerField()),
                ('property', models.ManyToManyField(to='estate.property')),
            ],
        ),
    ]
