# Generated by Django 5.0.1 on 2024-01-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=29800, max_digits=10),
            preserve_default=False,
        ),
    ]
