# Generated by Django 5.0.1 on 2024-01-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_property_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Investments'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-amount'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertystatus',
            options={'ordering': ['status'], 'verbose_name_plural': 'Property Statuses'},
        ),
    ]
