# Generated by Django 5.0.1 on 2024-01-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_alter_investment_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='account_type',
            field=models.CharField(choices=[('USDT_TRC20', 'USDT TRC20'), ('USDT_ERC20', 'USDT ERC20'), ('BTC', 'BTC')], default='BTC', max_length=20),
            preserve_default=False,
        ),
    ]
